# Generated by Django 5.2.6 on 2025-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_ticket_unique_ordering_row_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
